#!/bin/sh
[ "$1" = check ] || exit 1
NAME=bypass

log(){
	 echo "$(date +'%Y-%m-%d %H:%M:%S') : $*" >> /var/log/$NAME.log
}

sleep 2
while ! curl -so /dev/null -m 3 www.baidu.com;do
	sleep 2
done
log "Check network status successful!"
