#!/bin/sh

uci -q batch <<-EOF >/dev/null 2>&1
	chmod +x /etc/init.d/AdGuardHome /usr/share/AdGuardHome/*
	delete ucitrack.@AdGuardHome[-1]
	add ucitrack AdGuardHome
	set ucitrack.@AdGuardHome[-1].init=AdGuardHome
	commit ucitrack
	delete AdGuardHome.AdGuardHome.ucitracktest
	/etc/init.d/AdGuardHome restart
EOF

rm -f /tmp/luci-indexcache
exit 0
