#!/bin/sh

uci -q batch <<-EOF >/dev/null
	delete ucitrack.@turboacc[-1]
	add ucitrack turboacc
	set ucitrack.@turboacc[-1].init=turboacc
	commit ucitrack
EOF

[ -f /sys/module/shortcut_fe/refcnt ] && {
uci -q del turboacc.config.sw_flow
uci commit turboacc
}

exit 0
