#!/bin/sh

chmod +x /etc/init.d/cloudreve

uci -q batch <<-EOF >/dev/null
	delete ucitrack.@cloudreve[-1]
	add ucitrack cloudreve
	set ucitrack.@cloudreve[-1].init=cloudreve
	commit ucitrack
EOF

rm -f /tmp/luci-indexcache
exit 0
