include $(TOPDIR)/rules.mk

PKG_NAME:=luci-app-socatg

PKG_LICENSE:=MIT
PKG_MAINTAINER:=drophair <https://github.com/big-tooth>

LUCI_TITLE:=LuCI Support for socatg
LUCI_PKGARCH:=all
LUCI_DEPENDS:=+socat

include $(TOPDIR)/feeds/luci/luci.mk

# call BuildPackage - OpenWrt buildroot signature
