#!/bin/sh

uci -q batch <<-EOF >/dev/null
	delete ucitrack.@docker[-1]
	add ucitrack docker
	set ucitrack.@docker[-1].init=docker
	commit ucitrack
EOF

rm -f /tmp/luci-indexcache
/etc/init.d/dockerd restart &
exit 0
